### ISSUE TITLE
Forgot the nop before plus?

### ISSUE THREAD

**Issue by mschuldt** [jamesbowman/ga144tools#6]
https://github.com/jamesbowman/ga144tools/blob/3754cebbd90491aa581ac177d1125f4a02a38f47/src/nt.ga#L149

This doesn't look like a case where it can be discarded

**Comment by jamesbowman** [comment]
I think that code is implementing a jump table; the call at line 144 wants to map 0,1,2 to WEST,SOUTH,EAST.

So the address computed by + can only be 0-63. So there's no carry from bit 8 to bit 9. So no nop required.

Does that sound reasonable?

**Comment by mschuldt** [comment]
yup, that sounds right. Thanks!
